# Generated by Django 3.2.9 on 2021-12-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Component name')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('door_type', models.CharField(choices=[('firedoor', 'Firesafe door'), ('smc', 'Entrance door')], default='Select Type', max_length=255, verbose_name='Type')),
                ('component_description', models.TextField(null=True, verbose_name='Component description')),
                ('product_type', models.IntegerField(choices=[(1, 'Lock'), (2, 'Handle'), (3, 'Viewer'), (4, 'Knocker'), (5, 'Letter plate'), (6, 'Hinges'), (7, 'Apertures'), (8, 'Numerals')], verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Component count')),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.componentsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=30, unique=True, verbose_name='Job number')),
                ('machining_time', models.IntegerField(null=True, verbose_name='Total machining time')),
                ('frame_size', models.IntegerField(verbose_name='Frame total length')),
                ('production_date', models.DateField(null=True, verbose_name='Production date')),
                ('door_type', models.CharField(choices=[('firedoor', 'Firesafe door'), ('smc', 'Entrance door')], default='Select Type', max_length=255, verbose_name='Type')),
                ('components', models.ManyToManyField(related_name='product', through='products.ProductComponent', to='products.ComponentsModel')),
            ],
        ),
        migrations.AddField(
            model_name='productcomponent',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmodel'),
        ),
        migrations.CreateModel(
            name='ComponentToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_time', models.IntegerField()),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='products.componentsmodel')),
                ('tools_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='tools.toolsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='componentsmodel',
            name='tools_req',
            field=models.ManyToManyField(through='products.ComponentToolsModel', to='tools.ToolsModel', verbose_name='Tools Required'),
        ),
    ]
