# Generated by Django 3.2.9 on 2021-12-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer name')),
                ('customer_email', models.CharField(max_length=50, null=True, verbose_name='e-mail')),
                ('customer_phone', models.CharField(max_length=30, null=True, verbose_name='Phone no.')),
            ],
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('green', 'Green'), ('black', 'Black'), ('blue', 'Blue'), ('red', 'Red'), ('rosewood', 'Rosewood'), ('oak', 'Oak')], default=('white', 'White'), max_length=255, verbose_name='Door colour'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='delivery_address',
            field=models.TextField(null=True, verbose_name='Delivery address'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='Delivery date'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='handing',
            field=models.CharField(choices=[('LI', 'Left - Open In'), ('LO', 'Left - Open Out'), ('RI', 'Right - Open In'), ('RO', 'Right - Open Out')], default=('LI', 'Left - Open In'), max_length=255, verbose_name='Door handing'),
        ),
        migrations.AlterField(
            model_name='componentsmodel',
            name='door_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe line'), ('regency', 'Regency line'), ('script', 'Script line')], default='Select Type', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='door_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe line'), ('regency', 'Regency line'), ('script', 'Script line')], default='Select Type', max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.customermodel'),
        ),
    ]
