# Generated by Django 3.2.9 on 2021-12-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsmodel_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsmodel',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
    ]
