# Generated by Django 3.2.9 on 2021-12-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_toolsmodel_image'),
        ('products', '0005_auto_20211207_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glass_name', models.CharField(max_length=255, verbose_name='Glass name')),
                ('glass_door_type', models.CharField(choices=[('firedoor', 'Firesafe line'), ('regency', 'Regency line'), ('script', 'Script line')], default=('firedoor', 'Firesafe line'), max_length=255, verbose_name='for door type')),
                ('stock', models.IntegerField(verbose_name='In stock')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='GlassToolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_time', models.IntegerField()),
                ('glass_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glass', to='products.glassmodel')),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glass_tool', to='tools.toolsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='glassmodel',
            name='tools_req',
            field=models.ManyToManyField(through='products.GlassToolModel', to='tools.ToolsModel', verbose_name='Tools Required'),
        ),
    ]
