# Generated by Django 3.2.9 on 2021-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20211207_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomponent',
            options={'verbose_name': 'Door component', 'verbose_name_plural': 'Door compoonents'},
        ),
        migrations.AlterField(
            model_name='doorstylemodel',
            name='style_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe line'), ('regency', 'Regency line'), ('script', 'Script line')], max_length=255, verbose_name='Door type'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='door_height',
            field=models.FloatField(default=0, verbose_name='Door height'),
        ),
    ]
