# Generated by Django 3.2.9 on 2021-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211207_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsmodel',
            name='door_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe line'), ('regency', 'Regency line'), ('script', 'Script line')], default=('firedoor', 'Firesafe line'), max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='componentsmodel',
            name='product_type',
            field=models.IntegerField(choices=[(1, 'Lock'), (2, 'Handle'), (3, 'Viewer'), (4, 'Knocker'), (5, 'Letter plate'), (6, 'Hinges'), (7, 'Apertures'), (8, 'Numerals')], default=(1, 'Lock'), verbose_name='Type'),
        ),
    ]
