# Generated by Django 3.2.9 on 2021-12-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20211207_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmodel',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='job_no',
            field=models.CharField(max_length=4, unique=True, verbose_name='Line number'),
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='JOB', max_length=20, verbose_name='Order Num.')),
                ('customer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.customermodel', verbose_name='Customer')),
            ],
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='order_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ordermodel', verbose_name='Order number'),
        ),
    ]
