# Generated by Django 3.2.9 on 2021-12-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211207_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name': ('Order',), 'verbose_name_plural': ('Orders',)},
        ),
        migrations.AlterModelOptions(
            name='productsmodel',
            options={'verbose_name': 'Door Order', 'verbose_name_plural': 'Door Orders'},
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='finished',
            field=models.BooleanField(editable=False, null=True, verbose_name='Finished?'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='job_no',
            field=models.CharField(default='0000', help_text='four digit line number', max_length=4, unique=True, verbose_name='Line number'),
        ),
    ]
