# Generated by Django 3.2.9 on 2021-12-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211207_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_number',
            field=models.CharField(default='JOB', help_text='order num. format - "JOB0000000"', max_length=20, verbose_name='Order Num.'),
        ),
    ]
