# Generated by Django 3.2.9 on 2021-12-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20211207_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsmodel',
            name='door_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe line'), ('regency', 'Regency line'), ('script', 'Script line')], default=('firedoor', 'Firesafe line'), max_length=255, verbose_name='Door type'),
        ),
        migrations.AlterField(
            model_name='doorstylemodel',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/styles/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='glassmodel',
            name='glass_door_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe line'), ('regency', 'Regency line'), ('script', 'Script line')], default=('firedoor', 'Firesafe line'), max_length=255, verbose_name='Door type'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='finished',
            field=models.BooleanField(default=False, editable=False, null=True, verbose_name='Finished?'),
        ),
        migrations.AlterUniqueTogether(
            name='productsmodel',
            unique_together={('order_num', 'job_no')},
        ),
    ]
