# Generated by Django 3.2.9 on 2021-12-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20211208_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentsmodel',
            name='product_type',
            field=models.IntegerField(choices=[('lock', 'Lock'), ('handle', 'Handle'), ('viewer', 'Viewer'), ('knocker', 'Knocker'), ('letter plate', 'Letter plate'), ('hinges', 'Hinges'), ('apertures', 'Apertures'), ('numerals', 'Numerals')], default=('lock', 'Lock'), verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='order_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.ordermodel', verbose_name='Order number'),
        ),
    ]
