# Generated by Django 3.2.9 on 2021-12-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20211209_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='component_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_id', to='products.componentsmodel'),
        ),
    ]
