# Generated by Django 3.2.9 on 2021-12-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_toolsmodel_total_run_time'),
        ('products', '0022_alter_productcomponent_component_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttoolsmodel',
            name='tools_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_tool', to='tools.toolsmodel'),
        ),
    ]
