# Generated by Django 3.2.9 on 2021-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_componenttoolsmodel_tools_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='glass',
            field=models.ForeignKey(default=None, on_delete=models.SET('None'), related_name='door_glass', to='products.glassmodel', verbose_name='Glass'),
        ),
    ]
