# Generated by Django 3.2.9 on 2021-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_alter_toolsmodel_tool_name'),
        ('products', '0024_alter_productsmodel_glass'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='trim_with',
            field=models.ForeignKey(default=3, on_delete=models.SET(1), related_name='trim_with', to='tools.toolsmodel', verbose_name='Trim with?'),
        ),
    ]
