# Generated by Django 3.2.9 on 2021-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_productsmodel_trim_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttoolsmodel',
            name='machine_time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='glasstoolmodel',
            name='machine_time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='machining_time',
            field=models.FloatField(editable=False, null=True, verbose_name='Total machining time'),
        ),
    ]
