# Generated by Django 3.2.9 on 2021-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20211212_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='job_no',
            field=models.CharField(default='0000', help_text='four digit line number', max_length=4, verbose_name='Line number'),
        ),
    ]
