# Generated by Django 3.2.9 on 2021-12-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_productsmodel_job_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttoolsmodel',
            name='component_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp', to='products.componentsmodel'),
        ),
        migrations.AlterField(
            model_name='productcomponent',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_id', to='products.productsmodel'),
        ),
    ]
