# Generated by Django 3.2.9 on 2021-12-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20211213_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
