# Generated by Django 3.2.9 on 2021-12-15 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20211215_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomponent',
            name='product_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='prod_id', to='products.productsmodel'),
        ),
    ]
