# Generated by Django 3.2.9 on 2021-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsmodel',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
