# Generated by Django 3.2.9 on 2021-12-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Component name')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=30, unique=True, verbose_name='Job number')),
                ('machining_time', models.IntegerField(null=True, verbose_name='Total machining time')),
                ('frame_size', models.IntegerField(verbose_name='Frame total length')),
                ('components', models.ManyToManyField(related_name='product', to='products.ComponentsModel')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_time', models.IntegerField()),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='products.componentsmodel')),
                ('tools_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='tools.toolsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='componentsmodel',
            name='tools_req',
            field=models.ManyToManyField(through='products.ComponentToolsModel', to='tools.ToolsModel', verbose_name='Tools Required'),
        ),
    ]
