# Generated by Django 3.2.9 on 2021-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsmodel',
            name='product_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe door'), ('smc', 'Entrance door')], default='Select Type', max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='product_type',
            field=models.CharField(choices=[('firedoor', 'Firesafe door'), ('smc', 'Entrance door')], default='Select Type', max_length=255, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='production_date',
            field=models.DateField(null=True, verbose_name='Production date'),
        ),
    ]
