# Generated by Django 3.2.9 on 2021-12-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211206_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentsmodel',
            name='component_description',
            field=models.TextField(null=True, verbose_name='Component description'),
        ),
    ]
