# Generated by Django 3.2.9 on 2021-12-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
            ],
        ),
        migrations.CreateModel(
            name='SectionModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='UserProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_start', models.DateTimeField(null=True, verbose_name='Work started')),
                ('prod_end', models.DateTimeField(null=True, verbose_name='Work ended')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.employeemodel')),
            ],
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='products',
            field=models.ManyToManyField(through='admin_app.UserProductModel', to='products.ProductsModel'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='section_id',
            field=models.ManyToManyField(related_name='employees', to='admin_app.SectionModels', verbose_name='Section name'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
