# Generated by Django 3.2.9 on 2021-12-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='CNC name')),
            ],
        ),
        migrations.CreateModel(
            name='MachineEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.employeemodel')),
                ('machine_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.machinemodel')),
            ],
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='machine',
            field=models.ManyToManyField(through='admin_app.MachineEmployeeModel', to='admin_app.MachineModel', verbose_name='Machine used'),
        ),
    ]
