# Generated by Django 3.2.9 on 2021-12-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20211207_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='machinemodel',
            options={'verbose_name': 'Machine', 'verbose_name_plural': 'Machines'},
        ),
    ]
