# Generated by Django 3.2.9 on 2021-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20211207_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=255, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.DeleteModel(
            name='SectionModels',
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='section_id',
            field=models.ManyToManyField(related_name='employees', to='admin_app.DepartmentModel', verbose_name='Department name'),
        ),
    ]
