# Generated by Django 3.2.9 on 2021-12-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_auto_20211207_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinemodel',
            name='machine_location',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='admin_app.departmentmodel', verbose_name='Machine location'),
        ),
    ]
