# Generated by Django 3.2.9 on 2021-12-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_employeemodel_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='section_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='id_num',
            field=models.IntegerField(default=None, unique=True, verbose_name='Employee id number'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='section_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='admin_app.DepartmentModel', verbose_name='Department name'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='machine_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='admin_app.departmentmodel', verbose_name='Machine location'),
        ),
    ]
