# Generated by Django 3.2.9 on 2021-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_auto_20211211_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductmodel',
            name='prod_end',
            field=models.DateTimeField(null=True, verbose_name='Work ended'),
        ),
        migrations.AlterField(
            model_name='userproductmodel',
            name='prod_start',
            field=models.DateTimeField(null=True, verbose_name='Work started'),
        ),
    ]
