# Generated by Django 3.2.9 on 2021-12-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20211213_1956'),
        ('admin_app', '0011_auto_20211211_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductmodel',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to='products.productsmodel'),
        ),
    ]
