# Generated by Django 3.2.9 on 2021-12-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255, verbose_name='Tool name')),
                ('type', models.CharField(max_length=255, null=True, verbose_name='Type')),
                ('stock', models.IntegerField(verbose_name='In stock')),
                ('max_run_time', models.IntegerField(null=True, verbose_name='Allowed use time (in seconds)')),
                ('description', models.TextField(null=True, verbose_name='Description')),
            ],
        ),
    ]
