# Generated by Django 3.2.9 on 2021-12-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_toolsmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolsmodel',
            options={'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
    ]
