# Generated by Django 3.2.9 on 2021-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_toolsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='img/tools/', verbose_name='Image'),
        ),
    ]
