# Generated by Django 3.2.9 on 2021-12-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_toolsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/tools/', verbose_name='Image'),
        ),
    ]
