# Generated by Django 3.2.9 on 2021-12-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20211207_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/tools/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='max_run_time',
            field=models.IntegerField(default=0, help_text='Maximum run time allowed before tool change - in minutes!', verbose_name='Allowed run time'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='tool_name',
            field=models.CharField(help_text='Short tool name', max_length=255, unique=True, verbose_name='Tool name'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='type',
            field=models.CharField(blank=True, help_text='PCD - HSS - Carbide', max_length=255, null=True, verbose_name='Type'),
        ),
    ]
