# Generated by Django 3.2.9 on 2021-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20211207_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/img/tools/', verbose_name='Image'),
        ),
    ]
