# Generated by Django 3.2.9 on 2021-12-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_toolsmodel_current_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='tool_name',
            field=models.CharField(help_text='Short tool name', max_length=255, verbose_name='Tool name'),
        ),
    ]
