# Generated by Django 3.2.9 on 2021-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_toolsmodel_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsmodel',
            name='feed_rate',
            field=models.IntegerField(default=5, verbose_name='Feed Rate'),
        ),
    ]
