# Generated by Django 3.2.9 on 2021-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_toolsmodel_feed_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='tool_name',
            field=models.CharField(help_text='Short tool name', max_length=255, unique=True, verbose_name='Tool name'),
        ),
    ]
