# Generated by Django 3.2.9 on 2021-12-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_alter_toolsmodel_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='current_run_time',
            field=models.FloatField(default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='max_run_time',
            field=models.FloatField(default=0, help_text='Maximum run time allowed before tool change - in minutes!', verbose_name='Allowed run time'),
        ),
    ]
