# Generated by Django 3.2.9 on 2021-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_auto_20211212_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='max_run_time',
            field=models.FloatField(default=0, verbose_name='Allowed run time'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='tool_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tool name'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type'),
        ),
    ]
