# Generated by Django 3.2.9 on 2021-12-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_auto_20211213_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsmodel',
            name='feed_rate',
            field=models.IntegerField(default=5, null=True, verbose_name='Feed Rate'),
        ),
        migrations.AlterField(
            model_name='toolsmodel',
            name='stock',
            field=models.IntegerField(default=0, null=True, verbose_name='In stock'),
        ),
    ]
